#!/usr/bin/env python3
import sys
from os.path import dirname, join

mylib = join(dirname(__file__), './src')
if not mylib in sys.path:
    sys.path.insert(0, mylib)

from pyipmi.util import PyTest
from pyipmi.util.config import PyOpts

if __name__ == '__main__':
    pyopts = PyOpts()
    pyopts.add_options()
    options, _ = pyopts.parser.parse_args()

    test = PyTest(options, True)
    sys.exit(test.run())
