#!/usr/bin/env python3
import sys
from os.path import dirname, join

mylib = join(dirname(__file__), './src')
if not mylib in sys.path:
    sys.path.insert(0, mylib)

from pyipmi.cmds.pyshell import PyShell

if __name__ == '__main__':
    PyShell().cmdloop()
